name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Validate commit message
        uses: wagoid/commitlint-github-action@v4

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run ci:test:unit

      - name: Install playwright browser
        run: npx playwright install --with-deps chromium

      - name: Run e2e tests
        run: npm run ci:test:e2e

      - name: Build
        run: npm run build
